resources:
  - name: tasmota-release
    icon: github-circle
    type: github-release
    check_every: 60m
    source:
      owner: arendst
      repository: Tasmota

deploy: &deploy_controller
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: appropriate/curl
  inputs:
    - name: tasmota-release
  run:
    path: sh
    args:
      - -ec
      - |
        function update() {
          firmware_name=$1
          echo "updating ${TARGET} with ${firmware_name}"
          curl -XPOST --digest \
           -s -o /dev/null -w ''%{http_code}'' \
           -H "Content-Type: multipart/form-data" \
           -F "u2=@tasmota-release/${firmware_name}" \
           http://${TARGET}/u2
          echo "done"
        }

        update "tasmota-minimal.bin"
        sleep 5

        while [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://${TARGET}/)" != "200" ]; do
          echo "Device not up, yet..."
          sleep 5
        done

        update "tasmota.bin"
    

jobs:
- name: deploy release to controllers
  serial: true
  plan:
  - get: tasmota-release

  - in_parallel:
    - task: upload to christmas device in kitchen 🎄
      params:
        TARGET: ((controller.christmas_kitchen))
      config:
        <<: *deploy_controller
    - task: upload to christmas device on balcony 🎄
      params:
        TARGET: ((controller.christmas_balcony))
      config:
        <<: *deploy_controller